# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NightmareTv.NightmareTV
PackageVersion: 2.1.88
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{9F3C1B84-6A2E-4E77-9E4B-0C6E4F5A21D7}_is1'
ReleaseDate: 2026-10-06
AppsAndFeaturesEntries:
- DisplayName: Nightmare TV 2.1.88
  ProductCode: '{9F3C1B84-6A2E-4E77-9E4B-0C6E4F5A21D7}_is1'
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\Nightmare TV'
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/zeze89/nightmare-tv-releases/releases/download/v2.1.88/Nightmare-2.1.88-Setup.exe
  InstallerSha256: DCE2E3E0C42EF246AAE1B281BB859177707BEC224DEBB76E4287BB6BB76EE225
ManifestType: installer
ManifestVersion: 1.12.0
