# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NightmareTv.NightmareTV
PackageVersion: 2.1.81
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{9F3C1B84-6A2E-4E77-9E4B-0C6E4F5A21D7}_is1'
ReleaseDate: 2026-09-25
AppsAndFeaturesEntries:
- DisplayName: Nightmare TV 2.1.81
  ProductCode: '{9F3C1B84-6A2E-4E77-9E4B-0C6E4F5A21D7}_is1'
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\Nightmare TV'
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/zeze89/nightmare-tv-releases/releases/download/v2.1.81/Nightmare-2.1.81-Setup.exe
  InstallerSha256: BC8EAC6D64987D594B4841D65136C47CEB577EA9B067F6EC75F25D5353A0D6E9
ManifestType: installer
ManifestVersion: 1.12.0
