# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NightmareTv.NightmareTV
PackageVersion: 2.1.87
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{9F3C1B84-6A2E-4E77-9E4B-0C6E4F5A21D7}_is1'
ReleaseDate: 2026-10-03
AppsAndFeaturesEntries:
- DisplayName: Nightmare TV 2.1.87
  ProductCode: '{9F3C1B84-6A2E-4E77-9E4B-0C6E4F5A21D7}_is1'
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\Nightmare TV'
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/zeze89/nightmare-tv-releases/releases/download/v2.1.87/Nightmare-2.1.87-Setup.exe
  InstallerSha256: 4961C70448F1E89BC12FC9AD73B779014D01FAB59A739FFEB8BAD6C2CB3694F8
ManifestType: installer
ManifestVersion: 1.12.0
